name: Info on push
run-name:   Info on push triggered by ${{github.actor}}
on: [push,workflow_dispatch]
jobs:
  basic-run:
    defaults:
        run:
          working-directory: ./scripts
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: run info script
          
        run: ./info_of_changes.sh
