name: Info on push
run-name:   ${{ github.actor }}
on: [push,workflow_dispatch]
jobs:
  basic-run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  

      - run: echo "-------------"
      - run: |
            commit_ids=$(git log --format="%H" -n 2)
      - run: |
            for commit_id in $commit_ids; 
              do
                eval "commit_$i=$commit_id"
                i=$((i + 1))
              done
      
      - run: echo "the commits that are going to be evaluated are (HEAD) $commit_1   and $commit_2 " 
